apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: LoadBalancer
  selector:
    app: prometheus
    component: core
  clusterIP: 10.23.245.125
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32575
    port: 9090
    protocol: TCP
    targetPort: 9090
